Add required Check job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,3 +52,21 @@ jobs:
       if: ${{ !cancelled() && matrix.lint }}
       # cspell:ignore golangci
       uses: golangci/golangci-lint-action@v3
+      with:
+        only-new-issues: true
+        skip-pkg-cache: true
+
+  check:
+    runs-on: ubuntu-latest
+    if: ${{ !cancelled() }}
+    needs:
+    - test
+    steps:
+    - name: Check
+      run: |
+        if [[ "${{ needs.test.result }}" == "success" ]]; then
+          echo -e "\e[32mSuccess\e[0m"
+        else
+          echo -e "\e[31mFailed\e[0m"
+          exit 1
+        fi
